import React from 'react';
import Footer from '../../Components/Footer/Footer';
import MainNavbar from '../../Components/Navbar/MainNavbar';
import Spacer from '../../Components/Spacer/Spacer';
import styles from "./privacypolicy.module.scss"

const PrivacyPolicy = () => {

    React.useEffect(() => {
        window.scrollTo(0, 0)
    }, [])

    return (<div className={styles.pageContainer}>
        <div className={styles.contentContainer}>

        </div>
        <div className={styles.contentContainer}>
            <MainNavbar updateSidebar={() => { }} navType="light" />
            <h1 className={styles.pageHead}>Privacy Policy
            </h1>
            <p className="primaryText">
                Thank you for visiting the UltraPharmRx website located at UltraPharmRx.com (the “Site”). The Site is an Internet property of UltraCore Meds, LLC (collectively, “UltraPharmRx,” “we,” “our” or “us”). The following UltraPharmRx Terms and Conditions (“Terms and Conditions”) are inclusive of the UltraPharmRx Privacy Policy (“Privacy Policy”), the Consent to Telehealth, the Frequently Asked Questions (“FAQ”) and any and all other applicable operating rules, policies, price schedules and other supplemental terms and conditions or documents that may be published from time to time, which are expressly incorporated herein by reference (collectively, the “Agreement”).
            </p>
            <p className="primaryText">
                Subject to your compliance with these Terms and Conditions, we hereby grant to you a personal, limited, revocable, non-exclusive, and nontransferable right to view, download, access, and use the Sites in the United States and to use the Services solely for your personal and non-commercial use and only as permitted under these Terms and Conditions, the Consent to Telehealth, and the Privacy Policy.
            </p>
            <p className="primaryText">
                Each end-user visitor to the Site (“user,” “you” or “your”) agrees to the terms of the Agreement, in their entirety when she/he: (a) accesses or uses the Site; (b) accesses and/or downloads any of the: (i) blog posts, text, audio, video, photographs, graphics, artwork, testimonials and/or other content featured on the Site, including erectile dysfunction (“ED”) related content (collectively, “Informational Content”); and/or (ii) links to third party websites, products and/or services (“Third-Party Links,” and together with the Informational Content, the “Content”); (c) accesses certain product review sections, message boards, comments sections, customer ratings and other interactive features of the Site (collectively, “Interactive Services”); (d) registers to receive the UltraPharmRx e-mail newsletter (“Newsletter”); (e) purchases any of the non-prescription items made available by and through the Site (collectively, the “UltraCore Meds Products”) as provided by UltraPharmRx; (f) purchases prescription medicines via the Site (“Prescription Medications,” and together with the UltraPharmRx Products, the “Products”), as same are prescribed by certain third-party licensed medical doctors (“Healthcare Providers”) that provide telemedicine-related services in connection with the Site (“Telemedicine Services”); and/or (g) utilizes the various contact forms and/or contact information made available on the Site as a means to contact directly, or request to be contacted by, UltraPharmRx (collectively, the “Contact Services,” and together with the Site, Content, Social Media Pages, UltraPharmRx Products, Newsletter, Prescription Medications and Telemedicine Services, the “Site Offerings”).
            </p>
            <p className="primaryText">
                Third-Party Links may not be under our control; therefore, we are not responsible for the information, products or services described thereon, or for the content of any Third-Party Links, including, without limitation, any link contained in a Third-Party Link, or any changes or updates to a Third-Party Link. We are providing these Third-Party Links to you only as a convenience, and the inclusion of any Third-Party Link does not necessarily imply endorsement of its content or any association with its operators. Your use of these Third-Party Links is at your own risk, and we are not liable to you in any way, either directly or indirectly, for any content, errors, damage or loss caused by or in connection with use of or reliance on information contained in or provided to or provided by Third-Party Links.
            </p>
            <strong>
                PLEASE REVIEW THE TERMS OF THE AGREEMENT CAREFULLY. IF A USER DOES NOT AGREE WITH THE TERMS OF THE AGREEMENT IN THEIR ENTIRETY, THAT USER IS NOT AUTHORIZED TO USE THE SITE OFFERINGS IN ANY MANNER OR FORM.
            </strong>
            <Spacer />
            <strong>
                NEW JERSEY STATE RESIDENTS ARE ENCOURAGED TO REVIEW THEIR RIGHTS UNDER THE AGREEMENT, AS PROVIDED UNDER THE NEW JERSEY TRUTH-IN-CONSUMER CONTRACT WARRANTY AND NOTICE ACT (“TCCWNA”).
            </strong>
            <h3>Disclaimers
            </h3>
            <p>You expressly agree that use of the site is solely at your sole risk. You acknowledge and understand that the Content and UltraPharmRx Products have not been evaluated by the US Food & Drug Administration (“FDA”). The Content, UltraPharmRx Products and other material made available by and through the Site Offerings: (a) are not intended to diagnose, treat, cure or prevent any medical condition or disease; (b) are not in any way intended as medical advice or as a substitute for medical advice and/or medical treatment; and (c) should only be used in conjunction with the guidance and care of your physician. You further understand that the UltraPharmRx Products and Prescription Medications are not intended for use by persons under eighteen (18) years of age. You understand and agree that some of the Content associated with the UltraPharmRx Products and/or the efficacy of the UltraPharmRx Products, is obtained from independent third-party sources, such as news agencies, scientific reports and/or scientific/research entities (collectively, “Third-Party Sources”). UltraPharmRx does not warrant or represent that such Content is error-free, and UltraPharmRx does not represent or endorse any Third-Party Sources or the methods that they use to arrive at their conclusions. All UltraPharmRx Product specifications, performance data and other related information made available via the Site Offerings is for informational and illustrative purposes only, and do not constitute a guarantee or representation that the UltraPharmRx Products will conform to such specifications or performance data. UltraPharmRx does not warrant or represent that the UltraPharmRx Products will provide you with any particular benefits, or that your results will match those of others who have used the UltraPharmRx Products. Individual results will vary from person to person, and are dependent on factors including pre-existing medical conditions, age, weight, body chemistry, diet and exercise regimen.
            </p>
            <p>You expressly agree that use of the site is solely at your sole risk. You acknowledge and understand that the Content and UltraPharmRx Products have not been evaluated by the US Food & Drug Administration (“FDA”). The Content, UltraPharmRx Products and other material made available by and through the Site Offerings: (a) are not intended to diagnose, treat, cure or prevent any medical condition or disease; (b) are not in any way intended as medical advice or as a substitute for medical advice and/or medical treatment; and (c) should only be used in conjunction with the guidance and care of your physician. You further understand that the UltraPharmRx Products and Prescription Medications are not intended for use by persons under eighteen (18) years of age. You understand and agree that some of the Content associated with the UltraPharmRx Products and/or the efficacy of the UltraPharmRx Products, is obtained from independent third-party sources, such as news agencies, scientific reports and/or scientific/research entities (collectively, “Third-Party Sources”). UltraPharmRx does not warrant or represent that such Content is error-free, and UltraPharmRx does not represent or endorse any Third-Party Sources or the methods that they use to arrive at their conclusions. All UltraPharmRx Product specifications, performance data and other related information made available via the Site Offerings is for informational and illustrative purposes only, and do not constitute a guarantee or representation that the UltraPharmRx Products will conform to such specifications or performance data. UltraPharmRx does not warrant or represent that the UltraPharmRx Products will provide you with any particular benefits, or that your results will match those of others who have used the UltraPharmRx Products. Individual results will vary from person to person, and are dependent on factors including pre-existing medical conditions, age, weight, body chemistry, diet and exercise regimen.
            </p>
            <h3>1. Scope;</h3>
            <p>You expressly agree that use of the site is solely at your sole risk. You acknowledge and understand that the Content and UltraPharmRx Products have not been evaluated by the US Food & Drug Administration (“FDA”). The Content, UltraPharmRx Products and other material made available by and through the Site Offerings: (a) are not intended to diagnose, treat, cure or prevent any medical condition or disease; (b) are not in any way intended as medical advice or as a substitute for medical advice and/or medical treatment; and (c) should only be used in conjunction with the guidance and care of your physician. You further understand that the UltraPharmRx Products and Prescription Medications are not intended for use by persons under eighteen (18) years of age. You understand and agree that some of the Content associated with the UltraPharmRx Products and/or the efficacy of the UltraPharmRx Products, is obtained from independent third-party sources, such as news agencies, scientific reports and/or scientific/research entities (collectively, “Third-Party Sources”). UltraPharmRx does not warrant or represent that such Content is error-free, and UltraPharmRx does not represent or endorse any Third-Party Sources or the methods that they use to arrive at their conclusions. All UltraPharmRx Product specifications, performance data and other related information made available via the Site Offerings is for informational and illustrative purposes only, and do not constitute a guarantee or representation that the UltraPharmRx Products will conform to such specifications or performance data. UltraPharmRx does not warrant or represent that the UltraPharmRx Products will provide you with any particular benefits, or that your results will match those of others who have used the UltraPharmRx Products. Individual results will vary from person to person, and are dependent on factors including pre-existing medical conditions, age, weight, body chemistry, diet and exercise regimen.
            </p>

        </div>
        <Footer />
    </div>);
}

export default PrivacyPolicy;